---
title: Considering some distributions' fits
---

```{r}
library(gcRegional)
```

```{r}
# nat_posterior_sample <-
#   readRDS(
#   system.file(
#   "extdata/2018-06-25 national trace burn thin sample.rds",
#   package = 'gcRegional'))
nat_posterior_sample <- readRDS('~/Documents/gc-regional-project/data/2018-07-02 national trace burn thin.rds')

parameters_to_fit <- 
  c("logit.b.f", "logit.b.m", "logit.b.msm", "log.dur.inf.symp.m", 
    "log.dur.inf.symp.msm", "log.dur.inf.symp.f", "log.dur.inf.asymp.m", 
    "log.dur.inf.asymp.f", "log.dur.inf.asymp.msm", "logit.symp.m", 
    "logit.symp.f", "logit.symp.msm")

load_priors()

nat_posterior_to_fit <- nat_posterior_sample[, parameters_to_fit]

param_names <- names(nat_posterior_to_fit)
param_names <- strsplit(param_names, "\\.")
transforms <- sapply(param_names, `[[`, 1)
param_names <- # get the transformation for each column
  sapply(param_names, function(x) paste(x[2:length(x)], collapse = "."))
colnames(nat_posterior_to_fit) <- param_names # rename columns without transformations
logit_cols <- which(transforms == 'logit')
log_cols <- setdiff(1:length(transforms), logit_cols)
nat_posterior_to_fit <- mutate_at(nat_posterior_to_fit, logit_cols, ilogit) # undo logit transforms
nat_posterior_to_fit <- mutate_at(nat_posterior_to_fit, log_cols, exp) # undo log transforms

fits <- lapply(1:length(param_names), function(x) {
  param_row <- which(gc_env$priors$parameter == param_names[[x]])
  fun <- as.character(gc_env$priors[[param_row, 2]])
  startvals <- switch(
    fun,
    gamma = list(shape = gc_env$priors[param_row, 3], rate = gc_env$priors[param_row, 4]),
    beta = list(shape1 = gc_env$priors[param_row, 3], shape2 = gc_env$priors[param_row, 4]),
    normal = NULL
  )
  fit <- MASS::fitdistr(
    x = nat_posterior_to_fit[, x],
    densfun = fun,
    start = startvals
  )
  return(list(
    fit = fit,
    param = param_names[[x]],
    fun = fun))
})

```

```{r}
library(ggplot2)

gc_env$distribution_density_lookup

for (i in 1:ncol(nat_posterior_to_fit)) {
  df <- nat_posterior_to_fit[,i, drop=F]
  colnames(df) = 'x'
  
  prior_df <- data.frame(
        x = seq(0, max(1, df$x), max(1,df$x)/1000),
        y = gc_env$distribution_density_lookup[[fits[[i]][['fun']]]](
          seq(0, max(1, df$x), max(1,df$x)/1000), 
          fits[[i]][['fit']][['estimate']][[1]], 
          fits[[i]][['fit']][['estimate']][[2]]))
  prior_df$y <- prior_df$y/max(prior_df$y)
  
  ggplot(df, aes(x = x)) + 
    geom_histogram(aes(y=..ncount..), bins = 100, fill = 'steelblue1', alpha=0.5) +
    # geom_density(aes(y=..scaled..), fill = 'steelblue1', alpha=0.5) + 
    geom_area(
      data = prior_df, 
      aes(y = y), alpha=0.5,
      color = 'black') + 
    xlab(colnames(nat_posterior_to_fit)[[i]])
  
  ggsave(paste0("~/Desktop/", colnames(nat_posterior_to_fit)[[i]], ".png"), dpi=300)
}

```
