---
title: Intervention Analysis
---

In this document, we'll present the following information: 

- Distribution of Cases, Prevalence, and Incidence
- Prevalence Time Trends in Simulated Intervention
- Additional Tests, Cases Averted, and Relative Reductions of Prevalence in Simulated Intervention

```{r dependencies}
library(tidyverse)
library(ggrepel)
library(reshape2)
library(magrittr)
devtools::load_all(".")
```

```{r import simulated intervention data, cache=T}
# sf_df <- readRDS(system.file("intervention_analysis/interventions_data_SF_new.rds", package = 'gcRegional')) 
# ba_df <- readRDS(system.file("intervention_analysis/interventions_data_BA_new.rds", package = 'gcRegional')) 
# df <- do.call(rbind.data.frame, list(
#   cbind.data.frame(site = 'SF', sf_df),
#   cbind.data.frame(site = 'BA', ba_df)
# ))
# rm(sf_df)
# rm(ba_df)

# # Set the values from the 1st week of the year to be exactly 
# # yearly values. I.e. round down from dates like 2009.019 to 2009. 
# # Note that .019 ~ 1/52.
# # df$year <- sapply(df$year, function(x) if (x %% 1 < .25) x - x%%1 else x)
# df$year <- ifelse(df$year %% 1 < .25, df$year - df$year%%1, df$year)
# df$site <- as.character(df$site)
# df$interv <- as.character(df$interv)
# df$population <- as.character(df$population)


# # We didn't end up looking at the quarter annual interventions 
# df %<>% filter(! interv %in% c('no_screening', 'universal_annual',
# 															 'universal_semi_annual'
# 															 ))

df <- readRDS(system.file("intervention_analysis/interventions.rds", package='gcRegional'))
```

# Distribution of Cases, Prevalence, and Incidence

```{r distribution of cases}
last_data_year_sf <- 2016
last_data_year_ba <- 2017


# Subset the data frame for just incident_cases in the last data year and one year
# prior, only populations of interest for the next plot, and just get the base_case.
df %>% 
  select(site, sim, interv, year, population, incident_cases) %>% 
  filter(
    interv == 'base_case',
    population %in% c('Black Male', 'Black Female', 'Other Male', 'Other Female', 'Hispanic Male', 'Hispanic Female', 'MSM'),
    (year %in% c(last_data_year_sf, last_data_year_sf-1) & site == 'SF') |
      (year %in% c(last_data_year_ba, last_data_year_ba-1) & site == 'BA')
  ) %>% 
  select(-interv) -> cases_df


# The incident_cases column is cumulative, so we will subtract the previous year from 
# the next year. We split up the operation for SF and BA because the last data years are
# different for each site.
cases_df <- do.call(rbind.data.frame, list(
  dcast(filter(cases_df, site == 'SF'), site + sim + population ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = `2016` - `2015`) %>% 
    select(-c(`2016`, `2015`)),
  dcast(filter(cases_df, site == 'BA'), site + sim + population ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = (`2017` - `2016`)) %>% 
    select(-c(`2017`, `2016`))
))

cases_df %>% 
  group_by(site, sim) %>% 
  mutate(fraction_of_all_incidents = incidents / sum(incidents)) -> fractions_of_incident_cases

summary_cases_df <- group_by(fractions_of_incident_cases, site, population) %>% 
  summarize(
    ci_high = quantile(fraction_of_all_incidents, 0.975,  na.rm = T),
    iq_high = quantile(fraction_of_all_incidents, 0.75,  na.rm = T),
    mean = mean(fraction_of_all_incidents, na.rm = T),
    iq_low = quantile(fraction_of_all_incidents, 0.25,  na.rm = T),
    ci_low = quantile(fraction_of_all_incidents, 0.025,  na.rm = T))

summary_cases_df$site <- sapply(as.character(summary_cases_df$site), function(x) c(BA = 'Baltimore', SF = 'San Francisco')[[x]])

write.csv(x = summary_cases_df, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'breakdown_of_case_distribution.csv'
))

model_estimated_incident_infections_breakdown <- ggplot(
  summary_cases_df,
  aes(
  x = population,
  y = 100*mean,
  ymax = 100*ci_high,
  ymin = 100*ci_low,
  lower = 100*iq_low,
  upper = 100*iq_high,
  fill = population
  )) + 
  geom_bar(stat = 'identity') + 
  geom_errorbar(stat = 'identity', width = 0.2, alpha=0.5) + 
  facet_wrap(~site) + 
  ylab("Percentage") + 
  xlab("Demographic Groups") + 
  ggtitle("Proportional Breakdown of Incident Infections") + 
  theme_bw() + 
  ylim(c(0,100)) + 
  theme(axis.text.x = element_text(angle = 25, vjust = 0.5), legend.position = 'none') 



sf_p_msm <- 
    read.delim(system.file(
      "extdata",
      paste("ssun_p_msm_", "SF", ".txt", sep = ""),
      package = 'gcRegional'
    ))


ba_p_msm <- 
    read.delim(system.file(
      "extdata",
      paste("ssun_p_msm_", "BA", ".txt", sep = ""),
      package = 'gcRegional'
    ))



sf_cases <- 
tibble::tribble(
      ~sex,     ~age,      ~race, ~cases,
			"F", "15-24",    "black",       62,
			"F", "25-39",    "black",       67,
			"M", "15-24",    "black",       93,
			"M", "25-39",    "black",      221,
			"F", "15-24", "hispanic",       27,
			"F", "25-39", "hispanic",       30,
			"M", "15-24", "hispanic",      127,
			"M", "25-39", "hispanic",      462,
			"F", "15-24",    "other",       78,
			"F", "25-39",    "other",      158,
			"M", "15-24",    "other",      319,
			"M", "25-39",    "other",     1971
  )


ba_cases <- 
tibble::tribble(
  ~sex,   ~age,      ~race, ~cases, 
	"M", "15-24",    "black",    608, 
	"M", "25-39",    "black",    723, 
	"M", "15-24", "hispanic",      8, 
	"M", "25-39", "hispanic",     18, 
	"M", "15-24",  	 "other",    207, 
	"M", "25-39",	 	 "other",    219, 
	"F", "15-24",    "black",    831, 
	"F", "25-39",    "black",    390, 
	"F", "15-24", "hispanic",      6, 
	"F", "25-39", "hispanic",      4, 
	"F", "15-24",    "other",    293, 
	"F", "25-39",    "other",    168
  )

reported_cases <- rbind.data.frame(
	cbind.data.frame(site = 'SF', sf_cases),
	cbind.data.frame(site = 'BA', ba_cases))

sf_p_msm_y <- sf_p_msm %>% filter(year == 2016, age_cat==1) %>% `[[`('p_msm')
sf_p_msm_o <- sf_p_msm %>% filter(year == 2016, age_cat==2) %>% `[[`('p_msm')
ba_p_msm_y <- ba_p_msm %>% filter(year == 2017, age_cat==1) %>% `[[`('p_msm')
ba_p_msm_o <- ba_p_msm %>% filter(year == 2017, age_cat==2) %>% `[[`('p_msm')

p_msm_site_age <- tibble::tribble(
	~site, ~sex, ~age, ~p_msm,
	'SF', 'F', '15-24', 0,
	'SF', 'F', '25-39', 0,
	'SF', 'M', '15-24', sf_p_msm_y,
	'SF', 'M', '25-39', sf_p_msm_o,
	'BA', 'F', '15-24', 0,
	'BA', 'F', '25-39', 0,
	'BA', 'M', '15-24', ba_p_msm_y,
	'BA', 'M', '25-39', ba_p_msm_o
)

reported_cases %<>% merge(p_msm_site_age)

reported_cases %<>% mutate(
	cases_in_msw = cases * (1-p_msm),
	cases_in_msm = cases * p_msm
	)

reported_cases %<>% select(site, sex, age, race, cases_in_msw, cases_in_msm) %>% 
	group_by(site, sex, race) %>% 
	summarize_if(is.numeric, sum)

reported_cases %<>% mutate(population = paste(str_to_title(race), c('F' = 'Female', 'M' = 'Male')[sex])) %>% 
	select(-c(sex, race))

reported_cases %<>% ungroup() %>% select(-sex)

reported_cases_msw <- reported_cases[,c('site', 'population', 'cases_in_msw')]
colnames(reported_cases_msw)[3] <- 'cases'

reported_cases_msm <- tibble::tribble(
	~site, ~population, ~cases,
	'SF', 'MSM', reported_cases %>% filter(site == 'SF') %>% `[[`('cases_in_msm') %>% sum(),
	'BA', 'MSM', reported_cases %>% filter(site == 'BA') %>% `[[`('cases_in_msm') %>% sum()
	)

reported_cases <- rbind.data.frame(reported_cases_msw, reported_cases_msm)

reported_cases %<>% mutate(site = c('SF' = 'San Francisco', 'BA' = 'Baltimore')[site])

reported_cases %<>% group_by(site) %>% mutate(proportion_of_cases = cases / sum(cases))

reported_cases %<>% select(-cases) %>% mutate(mean = proportion_of_cases,
																							ci_high = mean, ci_low = mean,
																							iq_high = mean, iq_low=mean) %>% select(-proportion_of_cases)

# compare_reported_cases_and_estimated_incidents_proportions <- 
diag_inc_comparison_df <- 
	do.call(rbind.data.frame, list(
		cbind.data.frame(variable = 'model_estimate', summary_cases_df), 
		cbind.data.frame(variable = 'reported_cases', reported_cases)))

diag_inc_comparison_df_errorbars <- diag_inc_comparison_df
diag_inc_comparison_df_errorbars[diag_inc_comparison_df_errorbars$variable == 'reported_cases',
	c('ci_high', 'iq_high', 'mean', 'iq_low', 'ci_low')] <- NA 



# model_estimated_incident_infections_breakdown + 
# 	geom_point(data = reported_cases, mapping = aes(x=population, y = 100*proportion_of_cases))

# colnames(reported_cases)

model_estimated_incident_infections_breakdown <- ggplot(
 diag_inc_comparison_df,
  aes(
  x = population,
  y = 100*mean,
  ymax = 100*ci_high,
  ymin = 100*ci_low,
  lower = 100*iq_low,
  upper = 100*iq_high,
  fill = variable,
	group = variable
  )) + 
  geom_bar(stat = 'identity', position=position_dodge()) + 
  geom_errorbar(data = diag_inc_comparison_df_errorbars,
								stat = 'identity', position=position_dodge(.85), width = 0.2, alpha=0.5) + 
	# geom_point(data = reported_cases, position = position_dodge(width=0.5), mapping = aes(x=population, y=100*proportion_of_cases, ymax=NULL, ymin=NULL, lower=NULL, upper=NULL, color = 'target', shape='target')) + 
  facet_wrap(~site) + 
  ylab("Percentage") + 
  xlab("Demographic Groups") + 
  ggtitle("Model Estimated Proportional Breakdown of Incident Infections", subtitle='Compared to Diagnosed and Reported Cases') + 
  theme_bw() + 
  ylim(c(0,100)) + 
	guides(fill=guide_legend(title='')) +
	scale_fill_manual(values = c('model_estimate' = '#2b8cbe', 'reported_cases' = '#fdbb84'),
										labels = c('model_estimate' = 'Model Estimated Proportional\nBreakdown of Incident Infections',
												 'reported_cases' = 'Proportional Breakdown of \nDiagnosed Cases')) + 
	scale_color_manual(values=c('target'='red', labels='Breakdown of Reported Cases')) + 
	scale_shape_manual(values=c('target'=15), labels=c('Breakdown of Reported Cases')) + 
	theme(axis.text.x = element_text(angle = 25, vjust = 0.5), legend.position = 'bottom') 




ggsave(plot = model_estimated_incident_infections_breakdown,
			 filename = file.path(
					system.file("intervention_analysis/figures/", package = 'gcRegional'),
					'distribution_of_cases.png'
					),
			 height = unit(5, 'in'))

```

```{r prevalence rate ratios}
all_pop_prev_df <- df %>% 
  select(
    c(
    "site",
    "sim",
    "interv",
    "year",
    "population",
    "population_size",
    "symptomatic_cases",
    "asymptomatic_cases"
    )) %>%
  filter(
    (site == 'SF' & year == 2016) | (site == 'BA' & year == 2017),
    interv == 'base_case',
    population == 'All') %>% 
  mutate(all_pop_prevalence = (asymptomatic_cases + symptomatic_cases) / population_size) %>% 
  select(-c(population, population_size, symptomatic_cases, interv, asymptomatic_cases, year))
  

prev_df <- df %>% 
  select(
    c(
    "site",
    "sim",
    "interv",
    "year",
    "population",
    "population_size",
    "symptomatic_cases",
    "asymptomatic_cases"
    )) %>%
  filter(
    (site == 'SF' & year == 2016) | (site == 'BA' & year == 2017),
    interv == 'base_case',
    population %in% c('Black Male', 'Black Female', 'Other Male', 'Other Female', 'Hispanic Male', 'Hispanic Female', 'MSM')) %>% 
  mutate(prevalence = (asymptomatic_cases + symptomatic_cases) / population_size) %>% 
  select(-c(population_size, symptomatic_cases, interv, asymptomatic_cases, year))

prev_df <- merge(prev_df, all_pop_prev_df, by = c('site', 'sim'))

prev_df %<>% mutate(RR = prevalence / all_pop_prevalence) %>% select(-prevalence, all_pop_prevalence)

prev_ci_df <- group_by(prev_df, site, population) %>% 
  summarise(
    mean = mean(RR, na.rm = T),
    ci_high = quantile(RR, 0.975, na.rm = T),
    ci_low = quantile(RR, 0.025, na.rm = T),
    iq_high = quantile(RR, 0.75, na.rm = T),
    iq_low = quantile(RR, 0.25, na.rm = T)
  )

prev_ci_df$site <- sapply(prev_ci_df$site, function(x) c(SF = 'San Francisco', BA = 'Baltimore')[[x]])

write.csv(x = prev_ci_df, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'prevalence_relative_rates.csv'
))


ggplot(prev_ci_df, aes(x = population, middle = mean, ymax = ci_high, ymin = ci_low, upper = iq_high, lower = iq_low, fill = population)) + 
  geom_boxplot(stat = 'identity') + 
  facet_grid(~site) + 
  geom_hline(aes(group = 1), yintercept = 1, linetype = 'dashed', color = 'red') + 
  theme_bw() + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 25, vjust = .5)) + 
  scale_y_log10() + 
  ylab("Prevalence Relative Rate (log-scale)") + 
  xlab("Demographic Groups")  + 
  ggtitle("Relative Rates of Prevalence")


ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'prevalence_relative_rates.png'
  ),
  height = unit(4, 'in'))
```

```{r incidence relative rates}
last_data_year_sf <- 2016
last_data_year_ba <- 2017


df %>% 
  select(site, sim, interv, year, population, population_size, incident_cases) %>% 
  filter(
    interv == 'base_case',
    population == 'All',
    (year %in% c(last_data_year_sf, last_data_year_sf-1) & site == 'SF') |
      (year %in% c(last_data_year_ba, last_data_year_ba-1) & site == 'BA')
  ) %>% 
  select(-interv, -population) -> all_pop_incidence_df

all_pop_incidence_df <- do.call(rbind.data.frame, list(
  dcast(filter(all_pop_incidence_df, site == 'SF') %>% select(-population_size), site + sim ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = `2016` - `2015`) %>% 
    select(-c(`2016`, `2015`)) %>% 
    merge(filter(all_pop_incidence_df, site == 'SF' & year == 2016) %>% select(sim, population_size), by = c('sim')),
  dcast(filter(all_pop_incidence_df, site == 'BA') %>% select(-population_size), site + sim ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = (`2017` - `2016`)) %>% 
    select(-c(`2017`, `2016`)) %>% 
    merge(filter(all_pop_incidence_df, site == 'BA' & year == 2017) %>% select(sim, population_size), by = c('sim'))
))

all_pop_incidence_df %<>% mutate(all_pop_incidence = incidents / population_size)

df %>% 
  select(site, sim, interv, year, population, population_size, incident_cases) %>% 
  filter(
    interv == 'base_case',
    population %in% c('Black Male', 'Black Female', 'Other Male', 'Other Female', 'Hispanic Male', 'Hispanic Female', 'MSM'),
    (year %in% c(last_data_year_sf, last_data_year_sf-1) & site == 'SF') |
      (year %in% c(last_data_year_ba, last_data_year_ba-1) & site == 'BA')
  ) %>% 
  select(-interv) -> incidence_df


# The incident_cases column is cumulative, so we will subtract the previous year from 
# the next year. We split up the operation for SF and BA because the last data years are
# different for each site.
incidence_df <- do.call(rbind.data.frame, list(
  dcast(filter(incidence_df, site == 'SF') %>% select(-population_size), site + sim + population ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = `2016` - `2015`) %>% 
    select(-c(`2016`, `2015`)) %>% 
    merge(filter(incidence_df, site == 'SF' & year == 2016) %>% select(sim, population, population_size), by = c('sim', 'population')),
  dcast(filter(incidence_df, site == 'BA') %>% select(-population_size), site + sim + population ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = (`2017` - `2016`)) %>% 
    select(-c(`2017`, `2016`)) %>% 
    merge(filter(incidence_df, site == 'BA' & year == 2017) %>% select(sim, population, population_size), by = c('sim', 'population'))
))

incidence_df %<>% mutate(incidence = incidents / population_size)
incidence_df %<>% merge(all_pop_incidence_df, by = c('site', 'sim'))
incidence_df %<>% mutate(RR = incidence / all_pop_incidence)

incidence_ci_df <- group_by(incidence_df, site, population) %>% 
  summarise(
    mean = mean(RR, na.rm = T),
    ci_high = quantile(RR, 0.975, na.rm = T),
    ci_low = quantile(RR, 0.025, na.rm = T),
    iq_high = quantile(RR, 0.75, na.rm = T),
    iq_low = quantile(RR, 0.25, na.rm = T)
  )

incidence_ci_df$site <- sapply(incidence_ci_df$site, function(x) c(SF = 'San Francisco', BA = 'Baltimore')[[x]])

write.csv(x = incidence_ci_df, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'incidence_relative_rates.csv'
))


ggplot(incidence_ci_df, aes(x = population, middle = mean, ymax = ci_high, ymin = ci_low, upper = iq_high, lower = iq_low, fill = population)) + 
  geom_boxplot(stat = 'identity') + 
  facet_grid(~site) + 
  geom_hline(aes(group = 1), yintercept = 1, linetype = 'dashed', color = 'red') + 
  theme_bw() + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 25, vjust = .5)) + 
  scale_y_log10() + 
  ylab("Incidence Relative Rate (log-scale)") + 
  xlab("Demographic Groups") + 
  ggtitle("Relative Rates of Incidence")

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'incidence_relative_rates.png'
  ),
  height = unit(4, 'in'))
```

# Intervention Analysis

```{r intervention descriptions}

pal1 <- RColorBrewer::brewer.pal(11, 'BrBG')
pal2 <- RColorBrewer::brewer.pal(11, 'RdBu')
pal3 <- RColorBrewer::brewer.pal(11, 'PiYG')
pal4 <- sapply(1:11, function(x) c(pal1[x], pal2[x], pal3[x]))
pal4 <- c(pal4[,-c(5,6,7)])[1:23]

# > pal4
#  [1] "#543005" "#67001F" "#8E0152" "#8C510A" "#B2182B" "#C51B7D" "#BF812D" "#D6604D"
#  [9] "#DE77AE" "#DFC27D" "#F4A582" "#F1B6DA" "#80CDC1" "#92C5DE" "#B8E186" "#35978F"
# [17] "#4393C3" "#7FBC41" "#01665E" 
# ltfu + van: "#2166AC" "#4D9221" "#003C30" "#053061"

intervention_descriptions <- tibble::tribble(
                                  ~shortnames,                                            ~names,       ~frequency,    ~color,
                                  "base_case",                                       "Base Case",      "base_case", "dimgrey",

                               "young_annual",                          "15-24 Annual Screening",         "annual", "#543005",
                          "young_semi_annual",                     "15-24 Semi-Annual Screening",    "semi_annual", "#8E0152",



ggsave(plot = model_estimated_incident_infections_breakdown,
			 filename = file.path(
					system.file("intervention_analysis/figures/", package = 'gcRegional'),
					'distribution_of_cases.png'
					),
			 height = unit(5, 'in'))

```

```{r prevalence rate ratios}
all_pop_prev_df <- df %>% 
  select(
    c(
    "site",
    "sim",
    "interv",
    "year",
    "population",
    "population_size",
    "symptomatic_cases",
    "asymptomatic_cases"
    )) %>%
  filter(
    (site == 'SF' & year == 2016) | (site == 'BA' & year == 2017),
    interv == 'base_case',
    population == 'All') %>% 
  mutate(all_pop_prevalence = (asymptomatic_cases + symptomatic_cases) / population_size) %>% 
  select(-c(population, population_size, symptomatic_cases, interv, asymptomatic_cases, year))
  

prev_df <- df %>% 
  select(
    c(
    "site",
    "sim",
    "interv",
    "year",
    "population",
    "population_size",
    "symptomatic_cases",
    "asymptomatic_cases"
    )) %>%
  filter(
    (site == 'SF' & year == 2016) | (site == 'BA' & year == 2017),
    interv == 'base_case',
    population %in% c('Black Male', 'Black Female', 'Other Male', 'Other Female', 'Hispanic Male', 'Hispanic Female', 'MSM')) %>% 
  mutate(prevalence = (asymptomatic_cases + symptomatic_cases) / population_size) %>% 
  select(-c(population_size, symptomatic_cases, interv, asymptomatic_cases, year))

prev_df <- merge(prev_df, all_pop_prev_df, by = c('site', 'sim'))

prev_df %<>% mutate(RR = prevalence / all_pop_prevalence) %>% select(-prevalence, all_pop_prevalence)

prev_ci_df <- group_by(prev_df, site, population) %>% 
  summarise(
    mean = mean(RR, na.rm = T),
    ci_high = quantile(RR, 0.975, na.rm = T),
    ci_low = quantile(RR, 0.025, na.rm = T),
    iq_high = quantile(RR, 0.75, na.rm = T),
    iq_low = quantile(RR, 0.25, na.rm = T)
  )

prev_ci_df$site <- sapply(prev_ci_df$site, function(x) c(SF = 'San Francisco', BA = 'Baltimore')[[x]])

write.csv(x = prev_ci_df, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'prevalence_relative_rates.csv'
))


ggplot(prev_ci_df, aes(x = population, middle = mean, ymax = ci_high, ymin = ci_low, upper = iq_high, lower = iq_low, fill = population)) + 
  geom_boxplot(stat = 'identity') + 
  facet_grid(~site) + 
  geom_hline(aes(group = 1), yintercept = 1, linetype = 'dashed', color = 'red') + 
  theme_bw() + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 25, vjust = .5)) + 
  scale_y_log10() + 
  ylab("Prevalence Relative Rate (log-scale)") + 
  xlab("Demographic Groups")  + 
  ggtitle("Relative Rates of Prevalence")


ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'prevalence_relative_rates.png'
  ),
  height = unit(4, 'in'))
```

```{r incidence relative rates}
last_data_year_sf <- 2016
last_data_year_ba <- 2017


df %>% 
  select(site, sim, interv, year, population, population_size, incident_cases) %>% 
  filter(
    interv == 'base_case',
    population == 'All',
    (year %in% c(last_data_year_sf, last_data_year_sf-1) & site == 'SF') |
      (year %in% c(last_data_year_ba, last_data_year_ba-1) & site == 'BA')
  ) %>% 
  select(-interv, -population) -> all_pop_incidence_df

all_pop_incidence_df <- do.call(rbind.data.frame, list(
  dcast(filter(all_pop_incidence_df, site == 'SF') %>% select(-population_size), site + sim ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = `2016` - `2015`) %>% 
    select(-c(`2016`, `2015`)) %>% 
    merge(filter(all_pop_incidence_df, site == 'SF' & year == 2016) %>% select(sim, population_size), by = c('sim')),
  dcast(filter(all_pop_incidence_df, site == 'BA') %>% select(-population_size), site + sim ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = (`2017` - `2016`)) %>% 
    select(-c(`2017`, `2016`)) %>% 
    merge(filter(all_pop_incidence_df, site == 'BA' & year == 2017) %>% select(sim, population_size), by = c('sim'))
))

all_pop_incidence_df %<>% mutate(all_pop_incidence = incidents / population_size)

df %>% 
  select(site, sim, interv, year, population, population_size, incident_cases) %>% 
  filter(
    interv == 'base_case',
    population %in% c('Black Male', 'Black Female', 'Other Male', 'Other Female', 'Hispanic Male', 'Hispanic Female', 'MSM'),
    (year %in% c(last_data_year_sf, last_data_year_sf-1) & site == 'SF') |
      (year %in% c(last_data_year_ba, last_data_year_ba-1) & site == 'BA')
  ) %>% 
  select(-interv) -> incidence_df


# The incident_cases column is cumulative, so we will subtract the previous year from 
# the next year. We split up the operation for SF and BA because the last data years are
# different for each site.
incidence_df <- do.call(rbind.data.frame, list(
  dcast(filter(incidence_df, site == 'SF') %>% select(-population_size), site + sim + population ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = `2016` - `2015`) %>% 
    select(-c(`2016`, `2015`)) %>% 
    merge(filter(incidence_df, site == 'SF' & year == 2016) %>% select(sim, population, population_size), by = c('sim', 'population')),
  dcast(filter(incidence_df, site == 'BA') %>% select(-population_size), site + sim + population ~ year, value.var = 'incident_cases') %>% 
    mutate(incidents = (`2017` - `2016`)) %>% 
    select(-c(`2017`, `2016`)) %>% 
    merge(filter(incidence_df, site == 'BA' & year == 2017) %>% select(sim, population, population_size), by = c('sim', 'population'))
))

incidence_df %<>% mutate(incidence = incidents / population_size)
incidence_df %<>% merge(all_pop_incidence_df, by = c('site', 'sim'))
incidence_df %<>% mutate(RR = incidence / all_pop_incidence)

incidence_ci_df <- group_by(incidence_df, site, population) %>% 
  summarise(
    mean = mean(RR, na.rm = T),
    ci_high = quantile(RR, 0.975, na.rm = T),
    ci_low = quantile(RR, 0.025, na.rm = T),
    iq_high = quantile(RR, 0.75, na.rm = T),
    iq_low = quantile(RR, 0.25, na.rm = T)
  )

incidence_ci_df$site <- sapply(incidence_ci_df$site, function(x) c(SF = 'San Francisco', BA = 'Baltimore')[[x]])

write.csv(x = incidence_ci_df, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'incidence_relative_rates.csv'
))


ggplot(incidence_ci_df, aes(x = population, middle = mean, ymax = ci_high, ymin = ci_low, upper = iq_high, lower = iq_low, fill = population)) + 
  geom_boxplot(stat = 'identity') + 
  facet_grid(~site) + 
  geom_hline(aes(group = 1), yintercept = 1, linetype = 'dashed', color = 'red') + 
  theme_bw() + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 25, vjust = .5)) + 
  scale_y_log10() + 
  ylab("Incidence Relative Rate (log-scale)") + 
  xlab("Demographic Groups") + 
  ggtitle("Relative Rates of Incidence")

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'incidence_relative_rates.png'
  ),
  height = unit(4, 'in'))
```

# Intervention Analysis

```{r intervention descriptions}

pal1 <- RColorBrewer::brewer.pal(11, 'BrBG')
pal2 <- RColorBrewer::brewer.pal(11, 'RdBu')
pal3 <- RColorBrewer::brewer.pal(11, 'PiYG')
pal4 <- sapply(1:11, function(x) c(pal1[x], pal2[x], pal3[x]))
pal4 <- c(pal4[,-c(5,6,7)])[1:23]

# > pal4
#  [1] "#543005" "#67001F" "#8E0152" "#8C510A" "#B2182B" "#C51B7D" "#BF812D" "#D6604D"
#  [9] "#DE77AE" "#DFC27D" "#F4A582" "#F1B6DA" "#80CDC1" "#92C5DE" "#B8E186" "#35978F"
# [17] "#4393C3" "#7FBC41" "#01665E" 
# ltfu + van: "#2166AC" "#4D9221" "#003C30" "#053061"

intervention_descriptions <- tibble::tribble(
                                  ~shortnames,                                            ~names,       ~frequency,    ~color,
                                  "base_case",                                       "Base Case",      "base_case", "dimgrey",

                               "young_annual",                          "15-24 Annual Screening",         "annual", "#543005",
                          "young_semi_annual",                     "15-24 Twice-Annual Screening",    "semi_annual", "#8E0152",

                        "female_young_annual",                   "Female 15-24 Annual Screening",         "annual", "#BF812D",
                   "female_young_semi_annual",              "Female 15-24 Twice-Annual Screening",    "semi_annual", "#D6604D",

                                 "MSM_annual",                            "MSM Annual Screening",         "annual", "#B8E186",
                            "MSM_semi_annual",                       "MSM Twice-Annual Screening",    "semi_annual", "#35978F",
                         "MSM_quarter_annual",                    "MSM Quarter-Annual Screening", "quarter_annual", "#4393C3",

                 "high_activity_young_annual",                "High Risk 15-24 Annual Screening",         "annual", "#543005",
            "high_activity_young_semi_annual",           "High Risk 15-24 Twice-Annual Screening",    "semi_annual", "#67001F",

          "high_activity_female_young_annual",         "High Risk 15-24 Female Annual Screening",         "annual", "#BF812D",
     "high_activity_female_young_semi_annual",    "High Risk 15-24 Female Twice-Annual Screening",    "semi_annual", "#D6604D",

                   "high_activity_MSM_annual",                  "High Risk MSM Annual Screening",         "annual", "#B8E186",
              "high_activity_MSM_semi_annual",             "High Risk MSM Twice-Annual Screening",    "semi_annual", "#35978F",
           "high_activity_MSM_quarter_annual",          "High Risk MSM Quarter-Annual Screening", "quarter_annual", "#4393C3",

                       "high_activity_annual",                      "High Risk Annual Screening",         "annual", "#7FBC41",
                  "high_activity_semi_annual",                 "High Risk Twice-Annual Screening",    "semi_annual", "#01665E",

                          "remove_ltfu_10pct",                                 "Remove 10% LTFU",           "ltfu", "#2166AC",
                          "remove_ltfu_20pct",                                 "Remove 20% LTFU",           "ltfu", "#4D9221",
      "remove_f_msm_10pct_and_msw_20pct_ltfu",                       "Remove 10% LTFU (20% MSW)",           "ltfu", "#003C30",
            "1year_high_activity_semi_annual",                         "Mobile Outreach Testing",    "semi_annual", "#053061"
  )


empirical_interventions <- c('remove_ltfu_10pct', 'remove_ltfu_20pct',
														 'remove_f_msm_10pct_and_msw_20pct_ltfu'
														 )

hypothetical_interventions <- c("high_activity_young_annual",
																"high_activity_young_semi_annual",
																"young_annual", 
																"young_semi_annual",
																"high_activity_MSM_annual",
																"high_activity_MSM_semi_annual",
																"high_activity_MSM_quarter_annual",
																"MSM_annual", 
																"MSM_semi_annual",
																"MSM_quarter_annual", 
																"high_activity_annual",
																"high_activity_semi_annual",
																"high_activity_female_young_annual",
																"high_activity_female_young_semi_annual",
																"female_young_annual",
																"female_young_semi_annual",
                                '1year_high_activity_semi_annual')
interventions <- setdiff(unique(df$interv), 'base_case')

# intervention_descriptions$color <- as.character(intervention_descriptions$color)
```

```{r prevalence in interventions analysis}
int_prev_df <- df %>% 
  select(
    c(
      "site",
      "sim",
      "interv",
      "year",
      "population",
      "population_size",
      "symptomatic_cases",
      "asymptomatic_cases"
      )) %>% 
  filter(population == "All") %>% 
  select(-population) %>% 
  mutate(prevalence = (asymptomatic_cases + symptomatic_cases) / population_size) %>% 
  select(-c(population_size, asymptomatic_cases, symptomatic_cases))

int_prev_ci_df <- group_by(int_prev_df, site, interv, year) %>% 
  summarise(mean = mean(prevalence, na.rm=T),
            ci_high = quantile(prevalence, 0.975, na.rm = T),
            ci_low = quantile(prevalence, 0.025, na.rm = T))

last_int_prev_data_points <- as.data.frame(do.call(
  rbind.data.frame,
  list(
    filter(int_prev_ci_df, site == 'BA', year == 2022),
    filter(int_prev_ci_df, site == 'SF', year == 2021)
  )))

int_prev_ci_df$site <-
  sapply(as.character(int_prev_ci_df$site), function(x)
  c(SF = 'San Francisco', BA = 'Baltimore')[[x]])

last_int_prev_data_points$site <-
  sapply(as.character(last_int_prev_data_points$site), function(x)
  c(SF = 'San Francisco', BA = 'Baltimore')[[x]])

int_prev_ci_df[int_prev_ci_df$site == 'San Francisco', 'year'] <- int_prev_ci_df[int_prev_ci_df$site == 'San Francisco', 'year'] - 2016
int_prev_ci_df[int_prev_ci_df$site == 'Baltimore', 'year'] <- int_prev_ci_df[int_prev_ci_df$site == 'Baltimore', 'year'] - 2017

int_prev_ci_df <- merge(int_prev_ci_df, intervention_descriptions, by.x = 'interv', by.y = 'shortnames', all.x = T)

last_int_prev_data_points[last_int_prev_data_points$site == 'San Francisco', 'year'] <-
  last_int_prev_data_points[last_int_prev_data_points$site == 'San Francisco', 'year'] - 2016
last_int_prev_data_points[last_int_prev_data_points$site == 'Baltimore', 'year'] <-
  last_int_prev_data_points[last_int_prev_data_points$site == 'Baltimore', 'year'] - 2017

last_int_prev_data_points <- merge(last_int_prev_data_points, intervention_descriptions, by.x = 'interv', by.y = 'shortnames', all.x = T)
last_int_prev_data_points$names <- ordered(last_int_prev_data_points$names, levels = rev(intervention_descriptions$names))

write.csv(x = last_int_prev_data_points, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'prevalence_in_interventions_after_5_years.csv'
))

write.csv(x = int_prev_ci_df, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'prevalence_in_interventions_in_all_years.csv'
))



make_interventions_prevalence_plot <- function(interventions_list) {
  ggplot(
    filter(
    int_prev_ci_df,
    year >= 0,
    year <= 5,
    interv %in% interventions_list
    ),
    aes(x = year, y = 100 * mean, color = names)
    ) +
    geom_line() +
  facet_wrap(~site) + 
  scale_x_continuous(
    breaks = seq(0, 5, by = 1), 
    limits = c(0, 9)) +
  geom_label_repel(
    data = filter(last_int_prev_data_points, interv %in% interventions_list),
    aes(
    x = year,
    y = 100*mean,
    group = interv,
    label = names,
    # color = names,
		fill = names
    ),
		color = 'black',
    segment.color = 'black',
    segment.size = 0.1,
    segment.alpha = 0.8,
		# fontface = 'bold',
		alpha = 0.95,
    nudge_x = 2.5,
    direction = 'y',
    size = 2.5
    ) +
  expand_limits(y = 0) + 
  ylab("Prevalence (%)") +
  xlab("Years After Intervention Start") + 
	ggtitle("Prevalence Estimates During the Intervention Time Period") + 
  theme_bw() + 
  theme(legend.position = 'none') + 
  scale_color_manual(values = setNames(intervention_descriptions$color, intervention_descriptions$names)) + 
	scale_fill_manual(values = setNames(sapply(intervention_descriptions$color,
																						 colorspace::lighten, amount=.85),
																			intervention_descriptions$names))
}



current_strategies_interventions_prevalence <- make_interventions_prevalence_plot(c(empirical_interventions, 'base_case'))

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'intervention_prevalence_current_strategies.png'
  ),
  height = unit(5, 'in'),
  width = unit(9, 'in'),
  plot = current_strategies_interventions_prevalence)


hypothetical_strategies_interventions_prevalence <- make_interventions_prevalence_plot(c('base_case', hypothetical_interventions))

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'intervention_prevalence_hypothetical.png'
  ),
  height = unit(5, 'in'),
  width = unit(9, 'in'),
  plot = hypothetical_strategies_interventions_prevalence)


main_strategies <- c('base_case', empirical_interventions,
										 hypothetical_interventions[!grepl('high', hypothetical_interventions)],
										 '1year_high_activity_semi_annual')
main_strategies_interventions_prevalence <- make_interventions_prevalence_plot(main_strategies)

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'intervention_prevalence_main.png'
  ),
  height = unit(7, 'in'),
  width = unit(9, 'in'),
  plot = main_strategies_interventions_prevalence)

hypothetical_ints_all_activity <- hypothetical_interventions[!grepl("high", hypothetical_interventions)]
hypothetical_all_activity_interventions_prevalence <- make_interventions_prevalence_plot(c('base_case', hypothetical_ints_all_activity, '1year_high_activity_semi_annual'))

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'intervention_prevalence_hypothetical_all_activity.png'
  ),
  height = unit(5, 'in'),
  width = unit(9, 'in'),
  plot = hypothetical_all_activity_interventions_prevalence)

hypothetical_ints_high_activity <- hypothetical_interventions[grepl("high", hypothetical_interventions)]
hypothetical_high_activity_interventions_prevalence <- make_interventions_prevalence_plot(c('base_case', setdiff(hypothetical_ints_high_activity, c('1year_high_activity_semi_annual', 'high_activity_annual', 'high_activity_semi_annual'))))

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'intervention_prevalence_hypothetical_high_activity.png'
  ),
  height = unit(5, 'in'),
  width = unit(10, 'in'),
  plot = hypothetical_high_activity_interventions_prevalence)

```

```{r intervention prevalence reduction rates}
int_prev_dcast <- dcast(int_prev_df, site + sim + year ~ interv)

for (interv in interventions) {
    int_prev_dcast[[interv]] = int_prev_dcast[[interv]] / int_prev_dcast[['base_case']]
}

int_prev_dcast %<>% select(-base_case)

relative_summary_df <- melt(int_prev_dcast, id.vars = c('site', 'sim', 'year'), variable.name = 'interv', value.name = 'prevalence')

relative_ci_df <- relative_summary_df %>%  
  group_by(site, interv, year) %>% 
  summarise(mean = mean(prevalence, na.rm = T), 
            ci_high = quantile(prevalence, 0.975, na.rm = T),
            iq_high = quantile(prevalence, 0.75, na.rm = T),
            ci_low = quantile(prevalence, 0.025, na.rm = T),
            iq_low = quantile(prevalence, 0.25, na.rm = T))

last_data_points_relative <- as.data.frame(do.call(
  rbind.data.frame,
  list(
    filter(relative_ci_df, site == 'BA', year == 2022),
    filter(relative_ci_df, site == 'SF', year == 2021)
  )))

last_data_points_relative$site <-
  sapply(as.character(last_data_points_relative$site), function(x)
  c(SF = 'San Francisco', BA = 'Baltimore')[[x]])

last_data_points_relative <- merge(last_data_points_relative, intervention_descriptions, by.x = 'interv', by.y = 'shortnames', all.x = T)
last_data_points_relative$names <- ordered(last_data_points_relative$names, levels = rev(intervention_descriptions$names))

write.csv(x = last_data_points_relative, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'relative_prevalence_reductions_in_interventions_after_5_years.csv'
))


make_relative_prevalence_reduction_plot <- function(interventions_list) {
  ggplot(
    filter(last_data_points_relative, interv %in% interventions_list),
    aes(
    x = names,
    middle = 100 - 100 * mean,
    ymax = 100 - 100 * ci_high,
    ymin = 100 - 100 * ci_low,
    upper = 100 - 100 * iq_high,
    lower = 100 - 100 * iq_low,
    fill = names
    )
    ) +
    geom_boxplot(stat = 'identity') +
    facet_wrap( ~ site) +
    coord_flip() +
    theme_bw() +
    theme(legend.position = 'none',
    axis.title.x = element_text(hjust = 1)) +
    xlab("") +
    ylab("Prevalence Reduction as a Percentage of Base Case Prevalence") +
    ylim(y = c(0, 100)) +
    ggtitle("Relative Reduction in Prevalence") +
    scale_fill_manual(values = setNames(
    sapply(intervention_descriptions$color, colorspace::lighten),
    intervention_descriptions$names
    ))
    
}

empirical_relative_reductions <- make_relative_prevalence_reduction_plot(empirical_interventions)

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'prevalence_ratio_in_last_year_empirical.png'
  ),
  height = unit(5, 'in'), 
  width = unit(9, 'in'),
  plot = empirical_relative_reductions)

hypothetical_relative_reductions <- make_relative_prevalence_reduction_plot(hypothetical_interventions)

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'prevalence_ratio_in_last_year_hypothetical.png'
  ),
  height = unit(5, 'in'), 
  width = unit(9, 'in'),
  plot = hypothetical_relative_reductions)


hypothetical_all_activity_relative_reductions <- make_relative_prevalence_reduction_plot(c(hypothetical_interventions[!grepl('high', hypothetical_interventions)], '1year_high_activity_semi_annual'))

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'prevalence_ratio_in_last_year_hypothetical_all_activity.png'
  ),
  height = unit(5, 'in'), 
  width = unit(9, 'in'),
  plot = hypothetical_all_activity_relative_reductions)

hypothetical_high_activity_relative_reductions <- make_relative_prevalence_reduction_plot(setdiff(hypothetical_interventions[grepl('high', hypothetical_interventions)], c('1year_high_activity_semi_annual', 'high_activity_annual', 'high_activity_semi_annual')))

ggsave(file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'prevalence_ratio_in_last_year_hypothetical_high_activity.png'
  ),
  height = unit(5, 'in'), 
  width = unit(9, 'in'),
  plot = hypothetical_high_activity_relative_reductions)

```


```{r interventions additional tests and cases averted}

# Data Preparation ----

# Prepare data to visualize additional tests compared to cases averted

# Filtering for relevant data
additional_tests_df <- df %>% 
  select(
    c(
      "site",
      "sim",
      "interv",
      "year",
      "population",
      "number_screened"
      )) %>% 
  filter(population == "All",
         (site == 'BA' & year == 2022) | 
           (site == 'SF' & year == 2021)
    ) %>% 
  select(-c(population, year))

# Recast the data so that the numbers of screened individuals appear in columns specific
# to each intervention instead of all in one column with another 'interv' column.
additional_tests_df %<>% dcast(site + sim ~ interv, value.var = 'number_screened')

# Compute number of additional tests relative to the base case
for (interv in interventions) {
    additional_tests_df[[interv]] = additional_tests_df[[interv]] / additional_tests_df[['base_case']]
}

# Melt the data so that interv becomes a column again and 
# so that the data is in a format useable with ggplot2.
additional_tests_df %<>% melt(id.vars = c('site', 'sim'), variable.name = 'interv')

# Remove 1 so that we are visualizing the relative increase (rather than relative rate).
additional_tests_df$value <- additional_tests_df$value - 1

# Summarize the data with interquartile ranges, confidence intervals, and mean.
additional_tests_df %<>%  
  group_by(site, interv) %>% 
  summarise(mean = mean(value, na.rm=T),
						median = median(value, na.rm = T), 
            ci_high = quantile(value, 0.975, na.rm = T),
            iq_high = quantile(value, 0.75, na.rm = T),
            ci_low = quantile(value, 0.025, na.rm = T),
            iq_low = quantile(value, 0.25, na.rm = T))


# Select relevant cases averted data.
cases_averted_df <- df %>% 
  select(
    c(
      "site",
      "sim",
      "interv",
      "year",
      "population",
      "incident_cases"
      )) %>% 
  filter(population == "All",
         (site == 'BA' & year == 2022) | 
           (site == 'SF' & year == 2021)
    ) %>% 
  select(-c(population, year))

# Recast data so that each intervention's incident cases is each a column.
cases_averted_df %<>% dcast(site + sim ~ interv, value.var = 'incident_cases')

# Compute incident cases in interventions as relative to the base case.
for (interv in interventions) {
    cases_averted_df[[interv]] = (cases_averted_df[['base_case']] - cases_averted_df[[interv]]) / cases_averted_df[['base_case']]
}

# Melt the data so that interventions' data all goes into one column again 
# so we can use ggplot2.
cases_averted_df %<>% melt(id.vars = c('site', 'sim'), variable.name = 'interv')

# Summarize the data with confidence intervals, interquartile ranges, and mean.
cases_averted_df %<>%  
  group_by(site, interv) %>% 
  summarise(mean = mean(value, na.rm=T),
						median = median(value, na.rm = T), 
            ci_high = quantile(value, 0.975, na.rm = T),
            iq_high = quantile(value, 0.75, na.rm = T),
            ci_low = quantile(value, 0.025, na.rm = T),
            iq_low = quantile(value, 0.25, na.rm = T))


#  Data needed to compute number needed to test
nnt_df <- df %>% 
  select(
    c(
      "site",
      "sim",
      "interv",
      "year",
      "population",
      "incident_cases",
			"number_screened"
      )) %>% 
  filter(population == "All",
         (site == 'BA' & year == 2022) | 
           (site == 'SF' & year == 2021)
    ) %>% 
  select(-c(year, population))

nnt_df_basecase <- filter(nnt_df, interv == 'base_case') %>% select(-interv)

nnt_df <- merge(nnt_df, nnt_df_basecase, by	= c('site', 'sim'))

nnt_df %<>% mutate(
	cases_averted = incident_cases.y - incident_cases.x,
	additional_tests = number_screened.x - number_screened.y) %>% 
  select(-c(incident_cases.y, incident_cases.x, number_screened.y, number_screened.x)) %>% 
  mutate(nnt = additional_tests / cases_averted) %>% 
	filter(interv != 'base_case') %>% 
	rename(value = nnt) # %>% 
	# select(-c('cases_averted', 'additional_tests'))



nnt_df %<>%  
  group_by(site, interv) %>% 
  summarise(# mean1 = mean(value, na.rm=T),
						mean = mean(additional_tests, na.rm=T) / mean(cases_averted, na.rm=T),
						median = median(value, na.rm = T), 
            ci_high = quantile(value, 0.975, na.rm = T),
            iq_high = quantile(value, 0.75, na.rm = T),
            ci_low = quantile(value, 0.025, na.rm = T),
            iq_low = quantile(value, 0.25, na.rm = T))

# Put the 2016/17 data in a column side-by-side with the 2021/22 data 
# so the former can be subtracted from the latter to get results from 
# only the intervention time period
# library(data.table)
# nnt_df_ba <- dcast(setDT(filter(nnt_df, site == 'BA')), site + sim + interv ~
# 									 year, value.var = c('number_screened', 'incident_cases'))
# nnt_df_sf <- dcast(setDT(filter(nnt_df, site == 'SF')), site + sim + interv ~
# 									 year, value.var = c('number_screened', 'incident_cases'))

# Subtract the 2016/17 data from the 21/22 data and put the dfs back together
# nnt_df_ba %<>% mutate(
# 	incident_cases = incident_cases_2022 - incident_cases_2017,
# 	number_screened = number_screened_2022 - number_screened_2017) %>% 
#   select(-c(number_screened_2017, number_screened_2022, incident_cases_2017, incident_cases_2022)) 
# 
# nnt_df_sf %<>% mutate(
# 	incident_cases = incident_cases_2021 - incident_cases_2016,
# 	number_screened = number_screened_2021 - number_screened_2016) %>% 
#   mutate(nnt = number_screened / incident_cases) %>% 
#   select(-c(number_screened_2016, number_screened_2021, incident_cases_2016, incident_cases_2021))
# 
# nnt_df <- rbind.data.frame(nnt_df_ba, nnt_df_sf)
# 

# Merge the data together.
nt_ca_df <- do.call(rbind, list(
  cbind.data.frame(variable = 'additional_tests', additional_tests_df),
  cbind.data.frame(variable = 'cases_averted', cases_averted_df),
	cbind.data.frame(variable = 'nnt', nnt_df)
))

# Replace variables with human readable names.
nt_ca_df$variable <-
  sapply(nt_ca_df$variable, function(x)
  c(additional_tests = 'Additional Tests (%)', 
		cases_averted = 'Infections Averted (%)', 
		nnt = 'Number Needed to Test')[[x]])


# Merge intervention descriptions into our data.
nt_ca_df <- merge(nt_ca_df, intervention_descriptions, by.x = 'interv', by.y = 'shortnames', all.x = T)

# Order the data frame by the intervention description names.
nt_ca_df$names <- ordered(nt_ca_df$names, rev(intervention_descriptions$names))

# Replace 'SF' and 'BA' with their real names.
nt_ca_df$site <-
  sapply(as.character(nt_ca_df$site), function(x)
  c(SF = 'San Francisco', BA = 'Baltimore')[[x]])

nt_ca_df[grepl('ltfu', nt_ca_df$interv) & nt_ca_df$variable == 'Additional Tests (%)', 
         c('mean', 'ci_high', 'ci_low', 'iq_high', 'iq_low')] <-
           NA
nt_ca_df[grepl('ltfu', nt_ca_df$interv) & nt_ca_df$variable == 'Number Needed to Test', 
         c('mean', 'ci_high', 'ci_low', 'iq_high', 'iq_low')] <-
           NA
           
write.csv(x = nt_ca_df, file = file.path(
  system.file(
    package = 'gcRegional',
    "intervention_analysis/data/"
  ),
  'additional_tests_(pct)_cases_averted_(pct)_and_nnt.csv'
))


# This function generates the plot of additional tests and cases averted 
# side by side for the specified site. 

# symlog <- function(x) format(ifelse(x >= 0, exp(x)-1, 1-exp(-x)), scientific = F)
# symlog_i <- function(x) ifelse(x >= 0, log(x+1), -log(1-x))

make_additional_tests_and_cases_averted_plot <- function(site, interventions_list, subtitle, include_nnt = F) {
  ggplot(filter(nt_ca_df, 
								site == !! site, 
								variable %in% c('Additional Tests (%)', 
																'Infections Averted (%)', 
																if (include_nnt) 'Number Needed to Test' else NULL), 
								interv %in% interventions_list)) + 
	geom_hline(data = data.frame(variable = c('Additional Tests (%)', 'Infections Averted (%)'), yintercept = c(NA, 0)), 
						 mapping = aes(yintercept=yintercept), color='red', alpha=0.5) + 
  geom_boxplot(
    stat = 'identity',
    aes(
    x = names,
    ymax = 100*ci_high,
    upper = 100*iq_high,
    middle = 100*median,
    lower = 100*iq_low,
    ymin = 100*ci_low,
    fill = names
    )
    ) + 
  ggtitle(paste0(c(`Baltimore` = 'A) ', `San Francisco` = 'B) ')[[site]], "Intervention Outcomes in ", site)) + 
  theme_bw() + 
  facet_wrap(~variable, scales = 'free_x') + 
  coord_flip()  +
  xlab("") + 
  expand_limits(y=0) + 
  theme(axis.title.x = element_text(hjust = 1), legend.position = 'none', 
				axis.text.x = element_text(hjust=.5),
				plot.margin = margin(10, 15, 10, 10)) + 
  ylab("Additional Tests and Infections Averted as a Percentage of the Base Case") + 
    scale_fill_manual(values = setNames(
      sapply(intervention_descriptions$color, colorspace::lighten),
      intervention_descriptions$names
    ))

}


# make_nnt_plot <- function(interventions_list) {

#   ggplot(filter(nt_ca_df, 
# 								variable == 'Number Needed to Test', 
# 								interv %in% interventions_list)) + 
# 	geom_hline(yintercept=symlog_i(0), linetype='dashed', color='dimgrey') + 
#   geom_boxplot(
#     stat = 'identity',
#     aes(
#     x = names,
#     ymax = sapply(ci_high, symlog_i),
#     upper = sapply(iq_high, symlog_i),
#     middle = sapply(median, symlog_i),
#     lower = sapply(iq_low, symlog_i),
#     ymin = sapply(ci_low, symlog_i),
#     fill = names
#     )
#     ) + 
#   ggtitle("Number Needed to Screen to Avert One Additional Infection") + 
#   theme_bw() + 
#   facet_wrap(~site, scales = 'free_x') + 
#   coord_flip()  +
#   xlab("") + 
# 	ylab("") + 
#   expand_limits(y=symlog_i(c(-1000,1000))) + 
#   theme(# axis.title.x = element_text(hjust = -1), 
# 				axis.text.x = element_text(hjust = -1),
# 				legend.position = 'none', 
# 				plot.margin = margin(10, 15, 10, 10)) + 
#   # ylab("Additional Tests and Cases Averted as a Percentage of the Base Case") + 
#     scale_fill_manual(values = setNames(
#       sapply(intervention_descriptions$color, colorspace::lighten),
#       intervention_descriptions$names
#     )) + 
# 	scale_y_continuous(labels = symlog, breaks = symlog_i(c( -1000, -100, -10,  0, 10, 100, 1000))) 
# }

# no_scientific_notation <- function(x) format(x, scientific=F)


# nnt_plot <- 
# 	make_nnt_plot(c(hypothetical_interventions[!grepl('high', hypothetical_interventions)], '1year_high_activity_semi_annual'))

# ggsave(
#   file.path(
#   system.file("intervention_analysis/figures/", package = 'gcRegional'),
#   'number_needed_to_treat_all_activity.png'
#   ),
#   height = unit(6, 'in'),
#   width = unit(9, 'in'),
#   plot = nnt_plot 
#   )

# nnt_plot_high <- 
# 	make_nnt_plot(hypothetical_interventions[grepl('high', hypothetical_interventions)])

# ggsave(
#   file.path(
#   system.file("intervention_analysis/figures/", package = 'gcRegional'),
#   'number_needed_to_treat_high_activity.png'
#   ),
#   height = unit(6, 'in'),
#   width = unit(9, 'in'),
#   plot = nnt_plot_high
#   )

# Additional Tests and Cases Averted - Baltimore, Empirical Interventions
additional_tests_and_cases_averted_ba_empirical <-
  make_additional_tests_and_cases_averted_plot('Baltimore', empirical_interventions)

ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'number_tested_cases_averted_nnt_baltimore_empirical.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = additional_tests_and_cases_averted_ba_empirical
  )
  

cases_averted_ltfu <-  ggplot(filter(nt_ca_df, 
							variable == 'Infections Averted (%)', 
							interv %in% empirical_interventions)) + 
# geom_hline(yintercept=0)+
geom_boxplot(
	stat = 'identity',
	aes(
	x = names,
	ymax = 100*ci_high,
	upper = 100*iq_high,
	middle = 100*median,
	lower = 100*iq_low,
	ymin = 100*ci_low,
	fill = names
	)
	) + 
ggtitle("Infections Averted in LTFU Interventions") + 
theme_bw() + 
facet_wrap(~site) + 
coord_flip()  +
xlab("") + 
expand_limits(y=0) + 
theme(axis.title.x = element_text(hjust = 1), legend.position = 'none', 
			axis.text.x = element_text(hjust=.5),
			plot.margin = margin(10, 15, 10, 10)) + 
ylab("Infections Averted as a Percentage of the Base Case") + 
	scale_fill_manual(values = setNames(
		sapply(intervention_descriptions$color, colorspace::lighten),
		intervention_descriptions$names
	))



ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'cases_averted_ltfu_scenarios.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = cases_averted_ltfu 
  )

# Additional Tests and Cases Averted - San Francisco, Empirical Interventions
additional_tests_and_cases_averted_sf_empirical <-
  make_additional_tests_and_cases_averted_plot('San Francisco', empirical_interventions)
ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'number_tested_and_cases_averted_sanfrancisco_empirical.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = additional_tests_and_cases_averted_sf_empirical
  )
  

# Additional Tests and Cases Averted - Baltimore, Hypothetical Interventions
additional_tests_and_cases_averted_ba_hypothetical <-
  make_additional_tests_and_cases_averted_plot('Baltimore', hypothetical_interventions)
ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'number_tested_and_cases_averted_baltimore_hypothetical.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = additional_tests_and_cases_averted_ba_hypothetical
  )

# additional_tests_and_cases_averted_ba_hypothetical +  
# 		scale_y_continuous(labels = function(x) format(x, scientific=F), trans = function(x) if (x >= 1) log(x) else -log(2-x))

  
# ggsave(
#   file.path(
#   system.file("intervention_analysis/figures/", package = 'gcRegional'),
#   'number_tested_cases_averted_nnt_baltimore_hypothetical_log.png'
#   ),
#   height = unit(6, 'in'),
#   width = unit(9, 'in'),
#   plot = additional_tests_and_cases_averted_ba_hypothetical +  
# 		# scale_y_continuous(labels = function(x) format(x, scientific=F), trans = function(x) if (x >= 1) log(x) else -log(2-x))
# 		scale_y_continuous(labels = symlog)
#   )
  

# Additional Tests and Cases Averted - San Francisco, Hypothetical Interventions
additional_tests_and_cases_averted_sf_hypothetical <-
  make_additional_tests_and_cases_averted_plot('San Francisco', hypothetical_interventions)
ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'number_tested_and_cases_averted_sanfrancisco_hypothetical.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = additional_tests_and_cases_averted_sf_hypothetical
  )

# ggsave(
#   file.path(
#   system.file("intervention_analysis/figures/", package = 'gcRegional'),
#   'number_tested_cases_averted_nnt_sanfrancisco_hypothetical_log.png'
#   ),
#   height = unit(6, 'in'),
#   width = unit(9, 'in'),
#   plot = additional_tests_and_cases_averted_sf_hypothetical + 
# 		scale_y_log10(labels = function(x) format(x, scientific=F))
#   )

# Additional Tests and Cases Averted - Baltimore, Hypothetical Interventions without High Activity Targeted
additional_tests_and_cases_averted_ba_hypothetical_all_activity <-
  make_additional_tests_and_cases_averted_plot('Baltimore', c(hypothetical_interventions[!grepl('high', hypothetical_interventions)], '1year_high_activity_semi_annual'), subtitle = 'Hypothetical Interventions')

ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'number_tested_and_cases_averted_baltimore_hypothetical_all_activity.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = additional_tests_and_cases_averted_ba_hypothetical_all_activity
  )

# ggsave(
#   file.path(
#   system.file("intervention_analysis/figures/", package = 'gcRegional'),
#   'number_tested_and_cases_averted_baltimore_hypothetical_all_activity_log.png'
#   ),
#   height = unit(6, 'in'),
#   width = unit(9, 'in'),
#   plot = additional_tests_and_cases_averted_ba_hypothetical_all_activity + 
# 		scale_y_log10(labels = no_scientific_notation)
#   )

  

# Additional Tests and Cases Averted - San Francisco, Hypothetical Interventions without High Activity Targeted
additional_tests_and_cases_averted_sf_hypothetical_all_activity <-
  make_additional_tests_and_cases_averted_plot('San Francisco', c(hypothetical_interventions[!grepl('high', hypothetical_interventions)], '1year_high_activity_semi_annual'), subtitle = 'Hypothetical Interventions')
ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'number_tested_and_cases_averted_sanfrancisco_hypothetical_all_activity.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = additional_tests_and_cases_averted_sf_hypothetical_all_activity
  )

# ggsave(
#   file.path(
#   system.file("intervention_analysis/figures/", package = 'gcRegional'),
#   'number_tested_and_cases_averted_sanfrancisco_hypothetical_all_activity.png'
#   ),
#   height = unit(6, 'in'),
#   width = unit(9, 'in'),
#   plot = additional_tests_and_cases_averted_sf_hypothetical_all_activity + 
# 		scale_y_log10(labels = no_scientific_notation)
#   )

# Additional Tests and Cases Averted - Baltimore, Hypothetical Interventions - Only High Activity Targeted
additional_tests_and_cases_averted_ba_hypothetical_high_activity <-
  make_additional_tests_and_cases_averted_plot('Baltimore', setdiff(hypothetical_interventions[grepl('high', hypothetical_interventions)], c('1year_high_activity_semi_annual', 'high_activity_annual', 'high_activity_semi_annual')), subtitle = 'Risk Targeted Hypothetical Interventions')
ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'number_tested_and_cases_averted_baltimore_hypothetical_high_activity.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = additional_tests_and_cases_averted_ba_hypothetical_high_activity
  )

# ggsave(
#   file.path(
#   system.file("intervention_analysis/figures/", package = 'gcRegional'),
#   'number_tested_and_cases_averted_baltimore_hypothetical_high_activity.png'
#   ),
#   height = unit(6, 'in'),
#   width = unit(9, 'in'),
#   plot = additional_tests_and_cases_averted_ba_hypothetical_high_activity + 
# 		scale_y_log10(labels = no_scientific_notation)
#   )
  

# Additional Tests and Cases Averted - San Francisco, Hypothetical Interventions - Only High Activity Targeted
additional_tests_and_cases_averted_sf_hypothetical_high_activity <-
  make_additional_tests_and_cases_averted_plot('San Francisco', setdiff(hypothetical_interventions[grepl('high', hypothetical_interventions)], c('1year_high_activity_semi_annual', 'high_activity_annual', 'high_activity_semi_annual')), subtitle = 'Risk Targeted Hypothetical Interventions')
ggsave(
  file.path(
  system.file("intervention_analysis/figures/", package = 'gcRegional'),
  'number_tested_and_cases_averted_sanfrancisco_hypothetical_high_activity.png'
  ),
  height = unit(6, 'in'),
  width = unit(9, 'in'),
  plot = additional_tests_and_cases_averted_sf_hypothetical_high_activity
  )

# ggsave(
#   file.path(
#   system.file("intervention_analysis/figures/", package = 'gcRegional'),
#   'number_tested_and_cases_averted_sanfrancisco_hypothetical_high_activity.png'
#   ),
#   height = unit(6, 'in'),
#   width = unit(9, 'in'),
#   plot = additional_tests_and_cases_averted_sf_hypothetical_high_activity +
# 		scale_y_log10(labels = no_scientific_notation)
#   )

```
