# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv_mult <- function(lhs, rhs) {
    .Call('_gcRegional_mv_mult', PACKAGE = 'gcRegional', lhs, rhs)
}

mat_mult <- function(a, b) {
    .Call('_gcRegional_mat_mult', PACKAGE = 'gcRegional', a, b)
}

gcSim <- function(x, dt, cm, nYrs, initPop, n_sa, births, births_sa, births_nsa, aging, aging_nsa, debug, quarterly, increase_risk_all_pops) {
    .Call('_gcRegional_gcSim', PACKAGE = 'gcRegional', x, dt, cm, nYrs, initPop, n_sa, births, births_sa, births_nsa, aging, aging_nsa, debug, quarterly, increase_risk_all_pops)
}

gcSim2 <- function(x, dt, cm, nYrs, initPop, n_sa, births, births_sa, births_nsa, aging, aging_nsa, debug, quarterly, increase_risk_all_pops) {
    .Call('_gcRegional_gcSim2', PACKAGE = 'gcRegional', x, dt, cm, nYrs, initPop, n_sa, births, births_sa, births_nsa, aging, aging_nsa, debug, quarterly, increase_risk_all_pops)
}

